# Generated by Django 5.1.4 on 2025-02-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='timer_seconds',
        ),
        migrations.RemoveField(
            model_name='task',
            name='timer_status',
        ),
    ]
